import { expect, test } from '@playwright/test';
import { authenticate, dismissTour } from './auth';

test('folders organize existing files, persist, sync and receive new files and uploads', async ({ page, context }, testInfo) => {
  await authenticate(page);
  const csrf = (await context.cookies()).find((c) => c.name === 'galley_csrf')!.value;
  const headers = { 'x-csrf-token': csrf };
  const created = await page.request.post('/api/projects', { headers, data: { name: `Folders ${Date.now()}` } });
  expect(created.status()).toBe(201);
  const { id } = await created.json();
  const existing = await page.request.post(`/api/projects/${id}/files`, { headers, data: { path: 'figures/existing.tex' } });
  expect(existing.status()).toBe(201);
  await page.goto(`/p/${id}`);
  await dismissTour(page);
  await expect(page.getByRole('button', { name: 'Folder figures', exact: true })).toBeVisible();
  await expect(page.locator('.fname', { hasText: 'existing.tex' })).toBeVisible();
  const other = await context.newPage();
  await other.goto(`/p/${id}`);
  await expect(other.locator('.cm-content')).toBeVisible();

  await page.getByRole('button', { name: 'New folder', exact: true }).click();
  await page.getByRole('textbox', { name: 'New folder path' }).fill('figures/plots');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Folder figures/plots', exact: true })).toBeVisible();
  await expect(other.getByRole('button', { name: 'Folder figures/plots', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'New file', exact: true }).click();
  await expect(page.getByRole('textbox', { name: 'New file path' })).toHaveValue('figures/plots/');
  await page.getByRole('textbox', { name: 'New file path' }).fill('figures/plots/chart.tex');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.locator('.fname', { hasText: 'chart.tex' })).toBeVisible();
  await page.locator('input[type="file"]').setInputFiles({ name: 'plot.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>') });
  await expect(page.locator('.fname', { hasText: 'plot.svg' })).toBeVisible();
  const list = await (await page.request.get(`/api/projects/${id}/files`)).json();
  expect(list.map((f: { path: string }) => f.path)).toContain('figures/plots/plot.svg');

  const folder = page.getByRole('button', { name: 'Folder figures', exact: true });
  await folder.click();
  await expect(page.locator('.fname', { hasText: 'chart.tex' })).toBeHidden();
  await folder.click();
  await expect(page.locator('.fname', { hasText: 'chart.tex' })).toBeVisible();
  await page.getByRole('button', { name: 'Use root', exact: true }).click();
  await page.getByRole('button', { name: 'New folder', exact: true }).click();
  await page.getByRole('textbox', { name: 'New folder path' }).fill('empty');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Folder empty', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Folder empty', exact: true })).toBeVisible();

  // The same panel supports mouse and keyboard resizing, and remembers its width after reload.
  const handle = page.getByRole('separator', { name: 'Resize sidebar' });
  const box = (await handle.boundingBox())!;
  const before = Number(await handle.getAttribute('aria-valuenow'));
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 100, box.y + box.height / 2);
  await page.mouse.up();
  await expect(handle).toHaveAttribute('aria-valuenow', String(before + 100));
  await handle.focus();
  await page.keyboard.press('ArrowRight');
  await expect(handle).toHaveAttribute('aria-valuenow', String(before + 120));
  await page.reload();
  await expect(handle).toHaveAttribute('aria-valuenow', String(before + 120));
  await page.screenshot({ path: testInfo.outputPath('files-desktop.png') });
  await page.setViewportSize({ width: 375, height: 800 });
  const drawerBox = (await page.getByRole('complementary', { name: 'Files', exact: true }).boundingBox())!;
  expect(drawerBox.x + drawerBox.width).toBeLessThanOrEqual(375);
  await expect(page.getByRole('button', { name: 'New folder', exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('files-mobile.png') });
  await page.setViewportSize({ width: 1280, height: 800 });
  await handle.dblclick();
  await expect(handle).toHaveAttribute('aria-valuenow', '280');
  const meta = await (await other.request.get(`/api/projects/${id}`)).json();
  await other.route(`**/api/projects/${id}`, (route) => route.fulfill({ json: { ...meta, role: 'viewer' } }));
  await other.reload();
  await expect(other.getByRole('button', { name: 'Folder empty', exact: true })).toBeVisible();
  await expect(other.getByRole('button', { name: 'New folder', exact: true })).toHaveCount(0);
  await expect(other.getByRole('button', { name: 'New file', exact: true })).toHaveCount(0);
  await expect(other.getByRole('button', { name: 'Upload', exact: true })).toHaveCount(0);
  await other.close();
});
